// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"emqx_exhooks/internal/biz"
	"emqx_exhooks/internal/conf"
	"emqx_exhooks/internal/data"
	"emqx_exhooks/internal/server"
	"emqx_exhooks/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	msgRepo := data.NewMqttMsgRepo(dataData, logger)
	msgUsecase := biz.NewMsgUsecase(msgRepo, logger)
	emqxHookProviderService := service.NewEmqxHookProviderService(msgUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, emqxHookProviderService, logger)
	httpServer := server.NewHTTPServer(confServer, emqxHookProviderService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
